### ISSUE TITLE
Support connecting with password

### ISSUE THREAD

**Issue by tkf** [tkf/emacs-ipython-notebook#10]
Notebook server can be protected by a password.
But currently EIN cannot connect to password-protected server.

http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html#security

I have no plan for implementing this feature.  If someone is interested in implementing this, patches are very welcome.

**Comment by yarikoptic** [comment]
running ipython server without this basic authentication on any public or semi-private box might be of a big security/data safety concern.  So I hope @tkf -- the ein-master himself -- would start using that ipython feature and thus reconsiders implementing support of it in ein. Thanks ;)

**Comment by tkf** [comment]
Yea I know... And there is Wakari web service out there using IPython notebook.  It will be cool to connect to it from Emacs.

But considering the trouble we had with, and workaround I needed to implement for http library in Emacs (url.el), I am not courageous enough yet.
