### ISSUE TITLE
EIN interfering with ansi-term hooks and keyboard bindings

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [tkf/emacs-ipython-notebook#101]
The following snippet allows me to move through my Emacs easily while I am in `char-mode` in `ansi-term` in Emacs.

``` lisp
(add-hook 'term-mode-hook
  (lambda()
    (define-key term-raw-map (kbd "M-J") 'windmove-left) 
    (define-key term-raw-map (kbd "M-L") 'windmove-right) 
    (define-key term-raw-map (kbd "M-I") 'windmove-up)   
    (define-key term-raw-map (kbd "M-K") 'windmove-down)   
    (define-key term-raw-map (kbd "M-F") 'toggle-maximize-buffer)  
    ))
```

but as soon as I enable EIN with:
`(require 'ein)` 

the ansi-term hook above stops working. 

Moreover, enabling EIN also:
- Prevents `M-x command` in `char mode` in `ansi-term` from working
- Makes Emacs ignore this line too: `(global-set-key (kbd "C-x C-b") 'helm-buffers-list)`, which I use to select buffers in `character mode` in `ansi-term` using [helm](https://github.com/emacs-helm/helm).

This is all with `Emacs 24.2.1` and with `ein-20130118.1403` (the one available at EPLA)

**Comment by tkf** [comment]
Hmm... I have no idea.  You can check what command is executed by the key you want by `<f1> k [KEYBINDS]`.  For example, `<f1> k M-J`.  I think it is a good starting point to check what function your Emacs tries to execute.

**Comment by amelio-vazquez-reina** [comment]
My fault. The problem came from another package. Sorry for the confusion and thanks for your quick response. Closing this ticket.
