### ISSUE TITLE
Integrating Preview Latex into Ein

### ISSUE THREAD

**Issue by burakbayramli** [tkf/emacs-ipython-notebook#108]
Is it possible to  use LateX previews inside Ein? Previewing already works for me inside a Tex buffer. Then I guess this post is a feature request, it is a probably a small setting or addition to make this work.

**Comment by tkf** [comment]
I think it is easier to use imaxima-make-image (see #23) than preview-latex to produce latex images in non-latex buffer such as EIN.  Or we can use functions in IPython to produce latex images.

Let me close this issue as we already have an issue to track this feature request.
