### ISSUE TITLE
Highlight indentation mode in code cell?

### ISSUE THREAD

**Issue by djthorne** [tkf/emacs-ipython-notebook#112]
A very low priority, but it would be great.

**Comment by tkf** [comment]
What do you mean by "indentation mode"?  If you want to activate some minor mode in notebook, use `ein:notebook-mode-hook`.

**Comment by djthorne** [comment]
Right. I should have been more specific. I have tried do activate
highlight-indentation-mode with the hook prior to posting my question (
https://github.com/antonj/Highlight-Indentation-for-Emacs/). I've tried it
with and without mumamo. Thanks for the quick reply!

**Comment by tkf** [comment]
I guess it would be hard to make it work with mumamo.  Mumamo is actually not needed for multi-language syntax highlighting now.  By default (i.e., `ein:notebook-multilang-mode` [1]), the highlighting should work without mumamo.  Does `(add-hook 'ein:notebook-mode-hook 'highlight-indentation-mode)` work?

[1] http://tkf.github.io/emacs-ipython-notebook/#ein:notebook-modes

**Comment by djthorne** [comment]
Unfortunately not. The background color used to demarcate code blocks is interfering. The hook is activating the minor mode, as the minor mode highlighting can be seen in the output sections.

**Comment by tkf** [comment]
I see.  EIN is doing some hack [1] to make highlighting work against multiple languages.  If you use `ein:notebook-python-mode` or `ein:notebook-plain-mode` then it probably works, but you lost sane highlighting.  Definite fix should wait until Emacs core support highlighting with multiple languages.  Let me close this issue until Emacs core is changed.

[1] It copies cell body to another buffer and "copy colors" from that buffer to the actually cell.  So, if you run `highlight-indentation-mode` (or some function from there) in that buffer it may work.

**Comment by tkf** [comment]
Wait sec, you think it is because of the background?  If so, do `M-x customize-face ein:cell-input-area RET` and uncheck "background".
