### ISSUE TITLE
mumamo compatibility problems with emacs-for-python

### ISSUE THREAD

**Issue by gabrielelanaro** [tkf/emacs-ipython-notebook#12]
Hi! I'm the mantainer of https://github.com/gabrielelanaro/emacs-for-python I'd really like to make my package compatible with ein.

Right now I'm having problems setting ein up, what I obtain is an "invalid file name" error message my mumamo when I open a notebook and head over a cell. The problem disappears when i manually load python-mode.

the relevant part of the initialization file is something like this:

```
(load-file "~/workspace/emacs-for-python/epy-init.el")

(add-to-list 'load-path "~/workspace/emacs-websocket/")
(add-to-list 'load-path "~/workspace/emacs-ipython-notebook/")
(add-to-list 'load-path "~/workspace/ein/zeroein/markdown-mode/")
(require 'markdown-mode)
(load-file "~/workspace/ein/zeroein/nxhtml/autostart.el")
(require 'ein)
```

If you comment emacs-for-python loading all is ok. I suspect this is something related to other things that gets loaded with python-mode (rope, other stuff..). There's a way I can disable them when loading python-mode in the mumamo environment?

**Comment by gabrielelanaro** [comment]
An update: the problem seems related to flymake (in epy-python.el):

```
(add-hook 'python-mode-hook 'flymake-find-file-hook)
```

I've solved in this way:

```
 (add-hook 'python-mode-hook (lambda () (if (buffer-file-name)
                    (flymake-mode))))
```

**Comment by tkf** [comment]
Yes that makes sense.  I have defadvice for flymake-can-syntax-check-file to the similar thing in my setup so I didn't notice.  I will add this tips in the document.  Thanks for reporting.
