### ISSUE TITLE
ein: [error] Error (error) while opening notebook list at the server 8888.

### ISSUE THREAD

**Issue by salvesis** [tkf/emacs-ipython-notebook#130]
## Check list
- [x] I read "Avoid standard Emacs traps" section in
  https://github.com/tkf/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] I checked that IPython works with the browser interface.
- [x] I checked that the problem was not due to badly compiled
  files.  Removing `*.elc` files from source directory of EIN and
  its dependencies did not solve the problem.
- [x] I checked that the libraries are loaded from intended place.
  (You can check the location in the "System info" section below)
## Description of the problem you have

ein: [error] Error (error) while opening notebook list at the server 8888.
## Steps to reproduce the problem
1. start ipython
2. M-x ein:notebooklist-open
## Expected output

notebook list buffer
## Your EIN configuration (in .emacs.d/init.el or somewhere else)

(require 'ein)
## Your IPython configuration
1. What is your IPython version? (run `ipython --version`): 1.1.0
2. How do you start IPython? (e.g., `ipython notebook --port 9999`): ipythin notebook --pylab inline
3. What is your IPython notebook port number or URL?: 8888
## Additional information (if any)

```
Windows 7 (32 bit) with Cygwin
curl -V => curl 7.29.0 (i686-pc-cygwin) ...

Debugger entered--Lisp error: (wrong-type-argument listp %url_effective\))
  request--curl-preprocess()
  byte-code("r^Hq\210\301 )\207" [buffer request--curl-preprocess] 1)
  request--curl-callback(#<process request curl> "finished\n")
```
## System info:

``` cl
("EIN system info"
 :emacs-version "GNU Emacs 24.3.1 (i386-mingw-nt6.1.7601)
 of 2013-03-17 on MARVIN"
 :emacs-bzr-version nil
 :window-system w32
 :emacs-variant nil
 :os
 (:uname "CYGWIN_NT-6.1 XXXXXXXX 1.7.20(0.266/5/3) 2013-06-07 11:11 i686 Cygwin
"
         :lsb-release nil)
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.2.1alpha2"
           :source-dir "c:/Users/XXXXXXXX/AppData/Roaming/.emacs.d/elpa/ein-20130710.2114/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20130803.1409/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.1")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20130526.1915/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20130503.2013/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20130503.2013/auto-complete.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20130324.1305/popup.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python"
         :path "c:/emacs-24.3/lisp/progmodes/python.elc"
         :featurep nil
         :version-var nil
         :version nil)
  (:name "python-mode"
         :path "~/.emacs.d/lisp/python-mode.el-6.1.1/python-mode.el"
         :featurep t
         :version-var nil
         :version nil)
  (:name "helm"
         :path "~/.emacs.d/elpa/helm-20130610.1808/helm.elc"
         :featurep t
         :version-var nil
         :version nil)))
```

**Comment by tkf** [comment]
Maybe this is an bug in request.el (when used in Windows).  I don't know how to fix, though.  Probably you can workaround this by not using curl `(setq request-backend 'url-retrieve)`.

**Comment by salvesis** [comment]
The workaround solved the problem. I'd rather use curl but I don't know how to fix request.el either.
