### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by twiecki** [tkf/emacs-ipython-notebook#135]
Hi,

Wanted to get back to using `ein` which I find a way superior interface to IPyNB than the web client but seems like it's currently broken (at least with IPython >= 1.0) and not being updated anymore. Are there plans for updating this at some point in the future? If not, perhaps this could be marked in the project or maybe someone else is willing to maintain this?

**Comment by tkf** [comment]
No!  I am still using it everyday.  I just haven't updated IPython for something like 6 months because I've been busy :)   I don't want use IPython without EIN so I will certainly update it at some point.  I will make a PR once I start the new version so that you can watch that PR.  Stay tuned!

**Comment by twiecki** [comment]
That's great to hear, thanks! I've been using EIN exclusively but it stopped working for me so I'm back with the webui for now but would like to change back.

**Comment by demon386** [comment]
Great to hear that! Thanks for the amazing work!

**Comment by jswhite97** [comment]
So happy to hear this!  I was getting nervous.
