### ISSUE TITLE
    REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.

### ISSUE THREAD

**Issue by kidmose** [tkf/emacs-ipython-notebook#161]
I'm trying out ein for the first time and encounter and error:

I installed it with `el-get` (Also new to this, freshly installed. `el-get` confirms that the ein installation was succesfull)

How I try to start it: 
1. `ipython notebook` (in a terminal, ipython 1.2.1)
2. `emacs` (24.3.1)
3. `M-x ein:notebooklist-open RET RET`

Ouput (`*Messages*`):

```
Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50auctex.el (source)...
Loading /usr/share/emacs/site-lisp/auctex.el (source)...done
Loading /usr/share/emacs/site-lisp/preview-latex.el (source)...done
Loading /etc/emacs/site-start.d/50auctex.el (source)...done
Loading /etc/emacs/site-start.d/50autoconf.el (source)...done
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Error while loading 50dictionaries-common: Symbol's value as variable is void: debian-aspell-only-dictionary-alist
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...
Loading cjk-enc...done
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...done
Loading /etc/emacs/site-start.d/50latex-cjk-thai.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.
ein: [error] Content list call http://127.0.0.1:8888/api/notebooks/ failed with status error.
```

Any suggestion on how to proceed in making this work?

**Comment by millejoh** [comment]
Sorry for the confusion, but if you are pulling from el-get then you are downloading my [fork](https://github.com/millejoh/emacs-ipython-notebook), which is only compatible with IPython 2.x and onwards. If you still want to run ein with earlier version of IPython you will need to download manually from [tkf's](https://github.com/tkf/emacs-ipython-notebook) github repo.

**Comment by kidmose** [comment]
No worries - I'm just happy that you take the time to contribute/help me. 

```
sudo apt-get remove ipython # to remove 1.2.1 
sudo pip install "ipython[notebook]" # to install 3.0.0 
```

.. and everything is fine. 
Thanks!
