### ISSUE TITLE
notebooks served by jupyterhub

### ISSUE THREAD

**Issue by JosefMikkelsen** [tkf/emacs-ipython-notebook#183]
I'm wondering if you have thoughts regarding ein's handling of notebooks served through [Jupyterhub](https://github.com/jupyterhub/jupyterhub).

Right now, ein can't open a notebook from a jupyterhub server, unless I have missed something obvious, which does happen.

Upon superficial inspection it looks to me like the main issue is authentication. The format of the URL parameter to the `ein:notebooklist-open` appears to need an extra `/user/foobar/` but that's easily handled without changes to the code.

**Comment by millejoh** [comment]
You have not missed anything obvious. Apart from the different REST API I believe ein will also have to learn how to handle redirects. It's on my (steadily growing) list of things to do. Keep an eye on https://github.com/millejoh/emacs-ipython-notebook, as that is where all the development currently is happening.

**Comment by JosefMikkelsen** [comment]
Ah, okie dokie. ty @millejoh !
