### ISSUE TITLE
emacs is dead when use ein

### ISSUE THREAD

**Issue by colorfulsky** [tkf/emacs-ipython-notebook#184]
It works well when I just use it.But,when I switch another application,and then go back,things is different.
![image](https://cloud.githubusercontent.com/assets/11696388/20243629/e2386c24-a99a-11e6-9a1e-27622e3777ba.png)

**Comment by millejoh** [comment]
What version of IPython/Jupyter notebook are you running? What is the output in the console where you are running the notebook server? Does this only seem to happen with certain notebooks?

**Comment by colorfulsky** [comment]
I use IPython 4.1.2 with anaconda,and the python's version is 3.5.If I use jupyter notebook in chrome ,it works well.However,I try it today,it seems to be fine.Certainly,my emacs works well,I usually use it to do gtd and programme python.Thanks for your attention!
