### ISSUE TITLE
zeroein load path

### ISSUE THREAD

**Issue by epatters** [tkf/emacs-ipython-notebook#19]
In order to get zeroein.el to load the ein elisp files, I had to change the load list from

`'("ein" "markdown-mode" "websocket" "python" "auto-complete" "popup" "fuzzy" "pos-tip" "smartrep")`

to

`'("ein/lisp" "markdown-mode" "websocket" "python" "auto-complete" "popup" "fuzzy" "pos-tip" "smartrep")`.

I don't know whether this issue is specific to my configuration (Emacs 23 on Debian).

**Comment by tkf** [comment]
Yes, your fix is right.  I should have fixed it.  I am going to fix it.  Thank you very much!

**Comment by tkf** [comment]
tkf/zeroein@e577e3e10dd13c4ebd228c7fc5d5cd920dc6bde8 fixes it
