### ISSUE TITLE
Have not been able to save notebooks: "Wrong type argument: arrayp, nil"

### ISSUE THREAD

**Issue by margolds** [tkf/emacs-ipython-notebook#190]
I have just installed Jupyter, as well as ein from Melpa. I am able to login using "ein:notebooklist-login", and then browse my notebooks with "ein:notebooklist-open". When I choose a notebook, I first notcie that it doesn't open the buffer frame for me, but perhaps this is an unrelated issue.

When I switch to the selected notebook buffer, I can execute cells, but cannot save. I get the error "Wrong type argument: arrayp, nil".

Will gladly provide more info if needed.

**Comment by margolds** [comment]
I have tried debugging following your instructions from other issues. I restarted emacs and ran `M-x ein:dev-start-debug`. Then I ran `M-x ein:notebooklist-open`, and opened a notebook. At this point the debug buffer came up, attached:

[debug.txt](https://github.com/tkf/emacs-ipython-notebook/files/880511/debug.txt)

**Comment by millejoh** [comment]
What version of emacs are you running? This looks like the same problem as millejoh/emacs-ipython-notebook#190.

**Comment by bastibl** [comment]
Yes, that sounds exactly the problem that reported in the referenced issue.

**Comment by margolds** [comment]
Turns out I was running 24.5.1 on Fedora. Upgraded Fedora, upgraded emacs, all works now. Thanks!

**Comment by millejoh** [comment]
Moot since you are upgrading, but in case someone else stumbles upon this issue note that ein v12.1 (see [melpa stable]()http://stable.melpa.org/#/ein) still works with emacs 24.x.
