### ISSUE TITLE
Pressing tab to ident sometimes gives tracebacks

### ISSUE THREAD

**Issue by epatters** [tkf/emacs-ipython-notebook#20]
The following sequence reliably produces an error (running zeroein on Emacs 23):
1. Type `for i in xrange(10):` in an empty cell.
2. Press Enter.
3. Press Tab.

No tab is inserted, the cursor leaves the cell, and the following traceback is produced:

```
part 2 [python-mode]: chu-min=32 chu-max=33 chu-last-bol=nil
apply: Wrong length inserted in mirror [python-mode]: change-beg=10 part=3, chu-max=33, pm=34
Toggling font-lock-mode off; better pass an explicit argument.
```

**Comment by tkf** [comment]
Thanks for the report.  Yes, I noticed the problem.  I think this is because python.el and MuMaMo do not work well in this particular situation.  I just type `C-o` before hitting Tab to avoid this problem.  It's lame, but I don't know what is the best way to solve this problem.

**Comment by tkf** [comment]
BTW, you are using Fabián E. Gallina's python.el, right?  I am using it, so I don't know if it happens in other python modes.

**Comment by epatters** [comment]
Nope, I am using the vanilla python.el that ships with Emacs. (Although it looks like Gallina's version has just been merged into Emacs trunk, so I will be getting it sooner or later.)

Anyway, the trouble with that workaround is that it breaks my muscle memory. :)

But you've done a great job with the project. I've been hoping for a while that someone would take advantage of IPython's new client-server architecture to make a good Emacs client. Thanks for your hard work!

**Comment by tkf** [comment]
OK, I got a super dirty solution!

```
(defadvice mumamo-indent-line-function
  (around ein-workaround-mumamo-indent-line-function activate)
  (let (m)
    (unwind-protect
        (progn
          (insert "\n")
          (setq m (point-marker))
          (backward-char)
          ad-do-it)
      (save-excursion
        (goto-char m)
        (backward-char)
        (delete-char 1)))))
```

I will put this in my Emacs init.el for a while and see if it works properly.  If it is an OK-solution, I will probably put in EIN and make it possible to optionally enable (or disable).

Yea, I really like IPython's client-server architecture.  What is nice about it is that you can share server program with Vim guys. :)  I hope many other program languages follow this way.

**Comment by tkf** [comment]
A bit better version:

``` cl
(defadvice mumamo-indent-line-function
  (around ein-workaround-mumamo-indent-line-function activate)
  "Workaround the indentation problem when the cursor is at the
end of input area."
  (if (and (looking-at-p "\n")
           (get-char-property (point) 'read-only))
      (let (m)
        ;; The cursor is at the end of input area.
        ;; Indentation does not work as-is.  Here is the workaround:
        (unwind-protect
            (progn
              (insert "\n")
              (setq m (point-marker))
              (backward-char)
              ad-do-it)
          (save-excursion
            (goto-char m)
            (backward-char)
            (delete-char 1))))
    ad-do-it))
```

**Comment by tkf** [comment]
I added the above workaround code in master.
http://tkf.github.com/emacs-ipython-notebook/#ein:use-mumamo-indent-line-function-workaround

If you are using the above code, you can remove it after updating EIN.
