### ISSUE TITLE
ein: [error] Cannot open load file: mumamo-cmirr

### ISSUE THREAD

**Issue by nerduno** [tkf/emacs-ipython-notebook#39]
I'm attempting to install EIN.  The ein:notebooklist opens fine, but when I attempt to open a notebook, i receive the following error:
" Cannot open load file: mumamo-cmirr"

and the Notebook opens in the Fundamental mode.

Any suggestions?

Thanks,
Aaron

**Comment by tkf** [comment]
I guess you are using old version of nXhtml.  Please look at the directory where mumamo.el is (do `M-: (locate-library "mumamo") RET`, if you don't remember) and see if you have mumamo-cmirr.el.

If you want use mumamo based notebook mode, please install the newest version of nXhtml.

Quickest fix is to change ein:notebook-modes to avoid using MuMaMo:
http://tkf.github.com/emacs-ipython-notebook/#ein:notebook-modes

**Comment by tkf** [comment]
I removed mumamo-cmirr e6ad9bc9f3f6b46f220f5f624f57cd66c6abb586.
Probably it works without installing the newest nXhtml, as it looks like that you have mumamo.el.

**Comment by nerduno** [comment]
Thanks!  It appears that mumamo-cmirr is part of beta version 2.09 but not
2.08.  Thanks for the assistance.

ein:notebooklist-open still works, but when i try to open a notebook, I now
receive the following error:

Making mumamo-bug-3467-w14 local to  _temp_ while let-bound!
ein: [error] Wrong number of arguments: (lambda ... ...), 3

Any insight into this one?

Thanks,
Aaron

On Sat, Jul 21, 2012 at 4:37 AM, Takafumi Arakaki <
reply@reply.github.com

**Comment by nerduno** [comment]
I'll try updating to the 2.09 beta.

Thanks,
Aaron

**Comment by nerduno** [comment]
That solved the problem...  thanks.

-Aaron

**Comment by nerduno** [comment]
EIN is fantastic!  Thank you!

-Aaron

**Comment by tkf** [comment]
Great!  And thanks for the information about MuMaMo.  I should at least mention that EIN supports 2.09 in the document.  I need to check if it works on 2.08 and probably make a change if not.

I will close this issue.  Please reopen it or open another one if you still have problem.

**Comment by nerduno** [comment]
Thanks.  I opened up two new issues.

I also had a unrelated ipython notebook question...

I often access ipython notebook remotely (via ssh tunneling).  This works
well if I'm plotting inline in the notebook (using --pylab=inline),
However, I'm unable to get the ipython notebook to open up a separate
window for plots (i.e not use the matplotlib inline backend, but instead
using Qt4Agg for instance).

Interesting, if I ssh into the remote machine with X11 forwarding enabled,
then ipython qtconsole can plot into separate windows even when connected
to a remote kernel.  But for some reason this same solution does not work
for the ipython notebook.

Do you know a solution for this?

Thanks,
Aaron

On Sat, Jul 21, 2012 at 4:01 PM, Takafumi Arakaki <
reply@reply.github.com

**Comment by tkf** [comment]
I think this is because the DISPLAY environment variable.  You can check it with `os.getenv('DISPLAY')` in Python.

I guess you can connect to the server using `ssh -X`, check the DISPLAY value (do `echo $DISPLAY` in the shell) and then set it using `os.putenv`.  But I've never tried this method so I'm not sure if it works.  Let me know if it does :)

BTW, I guess IPython ML is more appropriate for this kind of question, as there are many knowledgeable people.

**Comment by nerduno** [comment]
what is IPython ML exactly?

On Sat, Jul 21, 2012 at 5:21 PM, Takafumi Arakaki <
reply@reply.github.com

**Comment by tkf** [comment]
This one http://mail.scipy.org/mailman/listinfo/ipython-user
