### ISSUE TITLE
Connecting to EIN Notebook with password security...

### ISSUE THREAD

**Issue by nerduno** [tkf/emacs-ipython-notebook#43]
When I attempt to connect to a notebook with password security, I receive an error.

Are notebooks with password security (set up using ipython config variable c.NotebookApp.password) accessible with EIN?

Thanks.

**Comment by tkf** [comment]
Sorry, currently EIN does not support password. #10

**Comment by nerduno** [comment]
Thanks for letting me know.

On Sat, Jul 21, 2012 at 4:35 PM, Takafumi Arakaki <
reply@reply.github.com
