### ISSUE TITLE
Sage support

### ISSUE THREAD

**Issue by syamajala** [tkf/emacs-ipython-notebook#47]
I'd really to be able to use something like this with sage. I gave it a try with Sage 5.2, running with IPython 0.13, but it just said ein: [error] Error (error) while opening notebook list at the server 8092. I'm unfamiliar with the IPython notebook but does it require a username and password to log in? I think that might be why it wasn't working.

**Comment by tkf** [comment]
Do you need password when using IPython notebook in Sage via web browser?  If you don't set it, IPython does not require username and password.  Also, when connecting IPython notebook in Sage via web browser, what is URL?  Can you see the notebook list at http://127.0.0.1:8092?  Or is it like http://127.0.0.1:8092/ipython (some sub-path is needed)?

**Comment by tkf** [comment]
Does Sage support IPython 0.13?  It looks like it is work in progress http://trac.sagemath.org/sage_trac/ticket/12719

**Comment by tkf** [comment]
I am closing it as no further information was provided.  Feel free to reopen the issue. :)
