### ISSUE TITLE
Error on opening notebook

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#49]
I just discovered ein by accident, and love the idea. I installed it on Emacs 24.1 (WIndows and OS X), fired up the iPython notebook,  and tried to open a notebook I'd previously created in my Web browser. Unfortunately, opening the file (on both systems) gives me the following error (here I'm copying what's shown in my _Messages_ buffer):

Contacting host: 127.0.0.1:8888
Opened notebook list at 8888
Open notebook analyze.
Contacting host: 127.0.0.1:8888
ein: [error] Wrong number of arguments: #[... "p\306 \307\310
\311\211   \311&+`p\211\312H>\204)

Actually, the error message is a lot longer than this, but I think it contains binary control characters that screw up my ability to paste it here... The only recognizable text in the error message is at the end,

[pretty-printer dll buffer pos new-ewoc old-buffer ewoc--dll-create vector cl-struct-ewoc nil ...] 9 ...], 4

Any idea what's going wrong? I'd love to get this running.

Thanks.

**Comment by tkf** [comment]
Hi, thanks for the report.  Did you compile the lisp files?  If so, can you try it again after removing them?  You can also try more verbose recording http://tkf.github.com/emacs-ipython-notebook/#reporting-issue.  I want to know how do you install EIN and wbesocket.el (el-get? MELPA? manual?) and the version number of them.

**Comment by rhstanton** [comment]
I did this two separate ways yesterday, with the same result each time:

1) The "quick try" method:

git clone git://github.com/tkf/zeroein.git
zeroein/zeroein.py

2) Installing using package.el after adding MELPA to my repository list.

I believe that both of these methods result in byte-compiling the lisp
files, but I also tried removing the .elc files from both ein and
websocket, and had the same results (the errors I sent you yesterday were
actually from this run).

ein:version = "0.1.2alpha0"
websocket-version = "0.92.1"

Best,

Richard

**Comment by tkf** [comment]
Thanks for the report.  If it didn't help, can you paste traceback?  Try `C-u M-x ein:dev-start-debug RET` then open notebook.  You will get `*Backtrace*` buffer so please paste what it has.  It is a better idea to open a small notebook with one or no cell.

See also:
http://tkf.github.com/emacs-ipython-notebook/#debugging

**Comment by rhstanton** [comment]
This is what happens when I click on "New Notebook"

Debugger entered--Lisp error: (wrong-number-of-arguments #[(pretty-printer &optional header footer) "p\306 \307\310
\311\211 \311&+`p \211\312H>\204)

**Comment by rhstanton** [comment]
Sending via email didn't seem to work too well! Here's another attempt:

This is what happens when I click on "New Notebook"

Debugger entered--Lisp error: (wrong-number-of-arguments #[(pretty-printer &optional header footer) "p\306 \307\310
\311\211   \311&+`p\211\312H>\204)\313\314\315\316#\210\317H\312H>\204>\313\314\320\316#\210\321Hq\210\322\216 \204N\323 !\204V\323! \324\325!I\210\326!\327#\326 \330#\"#\331    \"\"\210\332   #\"\210\312H>\204\206\313\333!\210\324\"I\210\312H>\204\231\313\334!\210\335#I\210.*\207" [pretty-printer dll buffer pos new-ewoc old-buffer ewoc--dll-create vector cl-struct-ewoc nil 0 error "%s accessing a non-%s" ewoc--dll ewoc 5 ewoc--buffer 1 ((set-buffer old-buffer)) "" 3 copy-marker ewoc--create-node #[(x) "c\207" [footer] 1] #[(x) "c\207" [header] 1] ewoc--node-enter-first ewoc--node-enter-last "ewoc--header storing a non-ewoc" "ewoc--footer storing a non-ewoc" 4 ewoc cl-struct-ewoc-tags header footer head foot] 9 ("/Applications/Emacs.app/Contents/Resources/site-lisp/dvc/lisp/ewoc.elc" . 18736)] 4)
  ewoc-create(ein:notebook-pp #("\n" 0 1 ...) nil t)
  ein:notebook-from-json([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil](:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...))
  ein:notebook-render()
  ein:notebook-request-open-callback([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil](:status nil :data ... :response-status 200))
  ein:notebook-request-open-callback-with-callback(([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback-with-callback ([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:funcall-packed (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:safe-funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:safe-funcall-packed (... :status nil :data ... :response-status 200))
  ein:query-ajax-callback(nil :timeout 60000 :parser ein:json-read :success (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :error (ein:query-default-error-callback . "http://127.0.0.1:8888/notebooks/0cb90698-dfa9-4649-9bc3-ba5a2493096d"))
  apply(ein:query-ajax-callback (nil :timeout 60000 :parser ein:json-read :success ... :error ...))
  url-http-activate-callback()
  url-http-content-length-after-change-function(319 423 104)
  url-http-wait-for-headers-change-function(1 432 431)
  url-http-generic-filter(#<process 127.0.0.1> "HTTP/1.1 200 OK
\nContent-Length: 103
\nContent-Disposition: attachment; filename=\"Untitled0.ipynb\"
\nServer: TornadoServer/2.1.1
\nLast-Modified: Wed, 15 Aug 2012 17:16:41 GMT
\nEtag: \"d0196f981d8ca623e6efb94f20048a11aa7bfe93\"
\nContent-Type: application/json
\nSet-Cookie: username=; expires=Tue, 16 Aug 2011 17:16:41 GMT; Path=/
\n
\n{\n \"metadata\": {\n  \"name\": \"Untitled0\"\n }, \n \"name\": \"Untitled0\", \n \"nbformat\": 2, \n \"worksheets\": []\n}")

**Comment by rhstanton** [comment]
And another try, this time deleting non-ASCII characters...

Debugger entered--Lisp error: (wrong-number-of-arguments #[(pretty-printer &optional header footer) "

[...]

 [pretty-printer dll buffer pos new-ewoc old-buffer ewoc--dll-create vector cl-struct-ewoc nil 0 error "%s accessing a non-%s" ewoc--dll ewoc 5 ewoc--buffer 1 ((set-buffer old-buffer)) "" 3 copy-marker ewoc--create-node #[(x) "c\207" [footer] 1] #[(x) "c\207" [header] 1] ewoc--node-enter-first ewoc--node-enter-last "ewoc--header storing a non-ewoc" "ewoc--footer storing a non-ewoc" 4 ewoc cl-struct-ewoc-tags header footer head foot] 9 ("/Applications/Emacs.app/Contents/Resources/site-lisp/dvc/lisp/ewoc.elc" . 18736)] 4)
  ewoc-create(ein:notebook-pp #("\n" 0 1 ...) nil t)
  ein:notebook-from-json([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil](:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...))
  ein:notebook-render()
  ein:notebook-request-open-callback([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil](:status nil :data ... :response-status 200))
  ein:notebook-request-open-callback-with-callback(([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback-with-callback ([cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:funcall-packed (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:safe-funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat 2 :name "Untitled0" :metadata ...) :response-status 200)
  apply(ein:safe-funcall-packed (... :status nil :data ... :response-status 200))
  ein:query-ajax-callback(nil :timeout 60000 :parser ein:json-read :success (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "0cb90698-dfa9-4649-9bc3-ba5a2493096d" ... nil nil nil nil ... "Untitled0" 2 nil nil nil nil] ein:notebook-pop-to-current-buffer nil) :error (ein:query-default-error-callback . "http://127.0.0.1:8888/notebooks/0cb90698-dfa9-4649-9bc3-ba5a2493096d"))
  apply(ein:query-ajax-callback (nil :timeout 60000 :parser ein:json-read :success ... :error ...))
  url-http-activate-callback()
  url-http-content-length-after-change-function(319 423 104)
  url-http-wait-for-headers-change-function(1 432 431)
  url-http-generic-filter(#<process 127.0.0.1> "HTTP/1.1 200 OK
\nContent-Length: 103
\nContent-Disposition: attachment; filename=\"Untitled0.ipynb\"
\nServer: TornadoServer/2.1.1
\nLast-Modified: Wed, 15 Aug 2012 17:16:41 GMT
\nEtag: \"d0196f981d8ca623e6efb94f20048a11aa7bfe93\"
\nContent-Type: application/json
\nSet-Cookie: username=; expires=Tue, 16 Aug 2011 17:16:41 GMT; Path=/
\n
\n{\n \"metadata\": {\n  \"name\": \"Untitled0\"\n }, \n \"name\": \"Untitled0\", \n \"nbformat\": 2, \n \"worksheets\": []\n}")

**Comment by tkf** [comment]
What is the version of Emacs you are using?  It is possible that EWOC shipped with your Emacs is too old for EIN.  Can you check the call signature of `ewoc-create`?  You can do this by `<f1> f ewoc-create RET`.  In my Emacs, it is:

```
(ewoc-create PRETTY-PRINTER &optional HEADER FOOTER NOSEP)
```

**Comment by rhstanton** [comment]
I’m using Emacs 24.1, and you may be right. Here’s what I get:

(ewoc-create PRETTY-PRINTER &optional HEADER FOOTER)

**Comment by tkf** [comment]
Too bad...  I thought 24 ships new EWOC.  I checked that 23.3 does in my machine.  Anyway, you can try new version of EWOC for example from here https://github.com/emacsmirror/ewoc.

I will add more helpful message in EIN so to help other user. Thanks for the info.

**Comment by rhstanton** [comment]
The notebook loads fine when I replace ewoc.el with the version you reference below. Thanks.

**Comment by rhstanton** [comment]
I just checked and Emacs 24.1.50.1 (the latest development version) has the same problem.

**Comment by tkf** [comment]
Strange...  In trunk ewoc-create has nosep http://bzr.savannah.gnu.org/lh/emacs/trunk/annotate/head:/lisp/emacs-lisp/ewoc.el#L228

Since 2006...
http://bzr.savannah.gnu.org/lh/emacs/trunk/revision/70969

**Comment by rhstanton** [comment]
Aha! I was loading an old version of ewoc.el that came with another package. The version with 24.1 seems fine (though this does suggest it’s time to dump the other package…)
