### ISSUE TITLE
Repo organization

### ISSUE THREAD

**Issue by fperez** [tkf/emacs-ipython-notebook#5]
Two notes on the repo:
- No COPYING or LICENSE file included, and it's not mentioned in the readme.  Personally I'd love it if you could license it BSD as the rest of IPython, but it's your choice (or not, if you have GPL dependencies).  In any case, you should have a license file and put a note of what the license is in the readme.
- I suggest you move all the top-level code into a subdir, so the main repo is a smaller directory with just the README, LICENSE and other necessary top-level files, plus subdirs.

**Comment by tkf** [comment]
Thanks for the advice.  Yes, I should have put LICENCE and mentioned it in README.  I mentioned it in the code but I guess it's better to be more verbose.  I will put them soon.

I am using GPL v3 as (I think) most of Emacs libraries use GPL and I thought it makes it easier to borrow their code when needed.  I considered BSD like IPython.  But I am relying on GPL licencing libraries so there is no way to distribute usable (without further download) EIN with IPython (I mean, if there is any chance).

About making sub-directories: I know that the current organization is ugly but I think there is no straight forward way to manage elisp library in sub-directories.  Some large projects such as helm use similar flat organization.  But I will think about it.  Probably putting all these files in `lisp/` directory is enough.

**Comment by fperez** [comment]
- Sounds like you need to go GPL here.  We won't be able to distribute them _together_, but that doesn't mean we can't advertise them prominently, maybe host the repo in ipython in the future, etc.
- Sure, just a `lisp/` dir would help a lot.
