### ISSUE TITLE
How to get titles displaying in a different font?

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#51]
I see various customize options in ein for what fonts to use to display different level titles, but my titles just display in Emacs as plain text, e.g.,
# Header 1
## Header 2

I'm probably missing something trivial, but how do I get them to display properly?

**Comment by rhstanton** [comment]
In the message above, I pasted two headers surrounded by single and double hash marks (which is how they're displayed in my Emacs buffer). However, when I submitted the comment, it was converted to display exactly as I'd like it to appear in Emacs! How do I achieve that in my Emacs buffer?

**Comment by tkf** [comment]
I guess you are typing "# Header 1" in markdown cell.  To get title with different size, you need to use heading cell (`C-c C-u <N>` where `<N>` is a number in 1-6).  If you want to change the size of markdown header, you can change markdown-header-face-1,2,...,6.  But it will effect when you edit normal markdown files.

BTW, if you want to show text as-is in issue comment, you can enclose it with triple backquotes.  Like this:

``````
```
# Header 1
## Header 2
```
``````

**Comment by rhstanton** [comment]
Thanks. When I get as far as C-c C-u, I'm offered a choice of only two options (c or m) after that, which seem to give me an input cell or a markdown cell respectively. What am I missing?

**Comment by tkf** [comment]
Oops I forgot to mention that heading cell is introduced in IPython 0.13.  You need to upgrade if you want headings.

**Comment by rhstanton** [comment]
Aha!
