### ISSUE TITLE
How to eliminate white border around plots?

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#52]
I tried to replicate one of the screenshots, showing a graph with a brown background in a zenburn-theme Emacs window. I downloaded the linked matplotlibrc file and plotted a graph, but instead of the entire background being brown, the graph had a white border around the outer part (including the axis labels), though it was correctly brown inside. Any suggestions for how to get rid of the white border? I'd upload a screen shot showing more exactly what I'm seeing, but I'm not sure how to do that.

**Comment by tkf** [comment]
You need to use IPython version after this fix:
https://github.com/ipython/ipython/pull/2074
Unfortunately, this is pulled after the latest release.

Meanwhile, you can monkey patch IPython.  I guess executing this before plotting works.  (or putting this in your ipyton_config.py).

``` python
from io import BytesIO

def print_figure(fig, fmt='png'):
    """Convert a figure to svg or png for inline display."""
    # When there's an empty figure, we shouldn't return anything, otherwise we
    # get big blank areas in the qt console.
    if not fig.axes and not fig.lines:
        return

    fc = fig.get_facecolor()
    ec = fig.get_edgecolor()
    # fig.set_facecolor('white')  # what's this for?
    # fig.set_edgecolor('white')
    try:
        bytes_io = BytesIO()
        fig.canvas.print_figure(bytes_io, format=fmt, bbox_inches='tight',
                                facecolor=fc, edgecolor=ec)  # <- ADDED
        data = bytes_io.getvalue()
    finally:
        fig.set_facecolor(fc)
        fig.set_edgecolor(ec)
    return data

import IPython.zmq.pylab.backend_inline
IPython.zmq.pylab.backend_inline.print_figure = print_figure
```

BTW, I don't think you can upload files to Github issue tracker.  You can upload it somewhere and paste it using Markdown markup.  (See the link "GitHub Flavored Markdown" at the top right of the comment text area.)

**Comment by rhstanton** [comment]
Thanks. A related but different question: Is there a way to customize the displayed size of graphs? They come out a bit small on my screen.

**Comment by tkf** [comment]
You can set 'savefig.dpi' and 'figure.figsize' in `c.InlineBackend.rc` in ipython_notebook_config.py.  It changes the image size saved in notebook file though.  Do you think it is smaller when it is opened in Emacs, comparing to browser?

**Comment by rhstanton** [comment]
On my system, yes. I'd say the linear dimensions are about 10% shorter in Emacs

**Comment by tkf** [comment]
Interesting.  I don't do any rescaling so it should be the same size.

**Comment by rhstanton** [comment]
I may have magnified my Web browser window, I suppose.
