### ISSUE TITLE
How to change background color in cells?

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#53]
Sorry to bombard you with messages...

I usually use the solarized-dark color theme, and with this theme all input cells with ein have a brown background. How can I change this to something closer to the blue used by default by this theme?

Thanks for a great tool!

**Comment by tkf** [comment]
You can control it by the background of the face `ein:cell-input-area`.
I guess `M-x customize-face ein:cell-input-area RET` is the easiest way.

**Comment by tkf** [comment]
Does it fix?  Please close the issue if so.

**Comment by rhstanton** [comment]
Fixed. Thanks.
