### ISSUE TITLE
Problem with single quote in markdown cell

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#54]
I have a single quote (used as an apostrophe) in the text in one of my markdown cells. Unfortunately, this seems to cause everything after it in the entire buffer to be highlighted as though inside a string. Of course, I could just use a different character, but shouldn't syntax highlighting be turned off in markdown cells? (Or is this just not possible?)

**Comment by tkf** [comment]
I can't reproduce the problem.  Probably you are using different version of markdown-mode.  Nevertheless, what you can do is to stop using markdown mode in markdown cell.

``` cl
(setq ein:mumamo-markdowncell-mode 'text-mode)
```

Syntax highlighting of multiple language in a single is difficult problem.  EIN is relying on the ability of MuMaMo and it looks like it is impossible to stop fontification mechanism.

**Comment by rhstanton** [comment]
I don't think I have MuMaMo installed. Maybe I should.

**Comment by tkf** [comment]
Ah, I see.  So whole buffer is parsed by python-mode.  Probably that is not a good default.

**Comment by rhstanton** [comment]
I just installed nxhtml (which comes with mumamo) and restarted Emacs. Now when I ask to create a new notebook, I get the following error backtrace:

'''
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (pos max) (mumamo-possible-chunk-forward pos max (lambda (pos max) "CHUNK-START-FUN" (ein:log (quote blather) "CHUNK-START-FUN(pos=%s max=%s)" pos max) (ein:aif (ein:mumamo-find-edge pos max nil (function ein:codecell-p)) (list it (if (functionp ein:mumamo-codecell-mode) ein:mumamo-codecell-mode ein:mumamo-fallback-mode) nil))) (lambda (pos max) "CHUNK-END-FUN" (ein:log (quote blather) "CHUNK-END-FUN(pos=%s max=%s)" pos max) (ein:mumamo-find-edge pos max t (function ein:codecell-p))))) 3)
  ein:mumamo-chunk-codecell(1 1 2)
  funcall(ein:mumamo-chunk-codecell 1 1 2)
  (let\* ... ... ... ...)
  (while --dolist-tail-- ... ... ... ...)
  (let ... ...)
  (cl--dolist ... ... ...)
  (catch ... ...)
  (cl--block-wrapper ...)
  (cl-block nil ...)
  (dolist ... ... ...)
  (progn ... ...)
  (if ... ...)
  (when ... ... ...)
  (progn ... ... ... ... ... ... ... ... ... ... ... ...)
  (if ... ...)
  (when ... ... ... ... ... ... ... ... ... ... ... ... ...)
  (if ... nil ...)
  (unless ... ...)
  (let\* ... ...)
  mumamo-find-next-chunk-values(nil nil nil nil)
  (setq this-new-values ...)
  (let ... ...)
  (while ... ... ... ...)
  (progn ... ...)
  (progn ...)
  (let\* ... ... ...)
  (mumamo-save-buffer-state nil ...)
  (if mumamo-find-chunk-is-active nil ... ... ... ... ...)
  (unless mumamo-find-chunk-is-active ... ... ... ... ...)
  (progn ... ... ...)
  (unwind-protect ... ...)
  (let ... ...)
  (save-match-data ... ... ...)
  (if this-new-chunk nil ...)
  (unless this-new-chunk ...)
  (let\* ... ... ... ... ... ... ... ...)
  (let\* ... ... ... ... ...)
  (save-restriction ... ...)
  mumamo-find-chunks-1(1 "mumamo-turn-on-actions")
  (let ... ... chunk)
  (progn ...)
  (if mumamo-multi-major-mode ...)
  (when mumamo-multi-major-mode ...)
  mumamo-find-chunks(1 "mumamo-turn-on-actions")
  (let\* ... ...)
  (if ... ... ...)
  (let ... ...)
  (if ... ... ... ... ... ... ...)
  mumamo-turn-on-actions(fundamental-mode)
  (let ... ... ... ... ... ... ... ... ...)
  ein:notebook-mumamo-mode()
  ein:notebook-mode()
  ein:notebook-render()
  ein:notebook-request-open-callback([cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#2 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #2 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#2 [#3 #2 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#2 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #2 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#2 [#3 #2 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#2 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #2 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#2 [#3 #2 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] :status nil :data (:worksheets nil :nbformat_minor 0 :nbformat 3 :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback [cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#2 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #2 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#2 [#3 #2 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#2 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #2 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#2 [#3 #2 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#2 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #2 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#2 [#3 #2 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil](:status nil :data ... :response-status 200))
  ein:notebook-request-open-callback-with-callback(([cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat_minor 0 :nbformat 3 :metadata ...) :response-status 200)
  apply(ein:notebook-request-open-callback-with-callback ([cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat_minor 0 :nbformat 3 :metadata ...) :response-status 200)
  apply(ein:funcall-packed (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) (:status nil :data ... :response-status 200))
  ein:safe-funcall-packed((ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) :status nil :data (:worksheets nil :nbformat_minor 0 :nbformat 3 :metadata ...) :response-status 200)
  apply(ein:safe-funcall-packed (... :status nil :data ... :response-status 200))
  ein:query-ajax-callback(nil :timeout 60000 :parser ein:json-read :success (ein:notebook-request-open-callback-with-callback [cl-struct-ein:$notebook 8888 "cc4a7f4d-f610-4731-88fa-3988285d7584" ... [cl-struct-ewoc #<buffer *ein: 8888/Untitled1*> ein:notebook-pp [[[#3 #4 "" #<marker at 2 in *ein: 8888/Untitled1*>] #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [[[#3 #4 DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] [#3 [#4 #3 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] "" #<marker at 2 in *ein: 8888/Untitled1*>] [[[#3 #4 #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] [#3 [#4 #3 "" #<marker at 2 in *ein: 8888/Untitled1*>] #("\n" 0 1 ...) #<marker at 1 in *ein: 8888/Untitled1*>] DL-LIST #<marker at 2 in *ein: 8888/Untitled1*>] nil insert] nil nil nil ... "Untitled1" 3 0 nil nil nil] ein:notebook-pop-to-current-buffer nil) :error (ein:query-default-error-callback . "http://127.0.0.1:8888/notebooks/cc4a7f4d-f610-4731-88fa-3988285d7584"))
  apply(ein:query-ajax-callback (nil :timeout 60000 :parser ein:json-read :success ... :error ...))
  url-http-activate-callback()
  url-http-content-length-after-change-function(318 419 101)
  url-http-wait-for-headers-change-function(1 428 427)
  url-http-generic-filter(#<process 127.0.0.1> "HTTP/1.1 200 OK
\nContent-Length: 100
\nContent-Disposition: attachment; filename=\"notebook.ipynb\"
\nServer: TornadoServer/2.1.1
\nLast-Modified: Wed, 15 Aug 2012 23:57:04 GMT
\nEtag: \"4fa14f649aeb470414833bdaa318c5832e1e9ad8\"
\nContent-Type: application/json
\nSet-Cookie: username=; expires=Tue, 16 Aug 2011 23:57:04 GMT; Path=/
\n
\n{\n \"metadata\": {\n  \"name\": \"Untitled1\"\n },\n \"nbformat\": 3,\n \"nbformat_minor\": 0,\n \"worksheets\": []\n}")

'''

**Comment by tkf** [comment]
It looks like the version problem again.  What version of mumamo you are using?  You can check it by `mumamo:version`.  Mine is 0.91.

Also, please check the call signature of `mumamo-find-next-chunk-values`.  I have this:

``` cl
(mumamo-find-next-chunk-values AFTER-CHUNK)
```

**Comment by rhstanton** [comment]
Mine also says it's  0.91, and the signature reports

(mumamo-find-next-chunk-values AFTER-CHUNK FROM AFTER-CHANGE-MAX
CHUNK-AT-AFTER-CHANGE)

Search forward for start of next chunk.
Return a list with chunk values for next chunk after AFTER-CHUNK
and some values for the chunk after it.

For the first chunk AFTER-CHUNK is nil.  Otherwise the values in stored in AFTER-CHUNK
is used to find the new chunk, its border etc.

**Comment by tkf** [comment]
OK, that means I can't rely on mumamo:version to identify the actual version.  How did you install nxhtml?  It should work if you install the latest developmental version.  I installed nxhtml from https://github.com/emacsmirror/nxhtml using el-get.  I guess easiest way to fetch it from zeroein/nxhtml/ since you already tried zeroein.

**Comment by rhstanton** [comment]
Thanks. Now it works – mostly. As I navigate around the notebook, I get frequent warnings:

Warning (mumamo-per-buffer-local-vars): Already 'permanent-local t: buffer-file-name
Warning (mumamo-per-buffer-local-vars): Already 'permanent-local t: buffer-file-name
[...]

**Comment by tkf** [comment]
Yes, sometime mumamo is too noisy.  I found it is especially annoying, even unable to use, when used with python-mode.el.  What python-mode are you using?  python.el or python-mode.el?

**Comment by rhstanton** [comment]
Python-mode. As you say, the errors (and associated buffer) pop up so often that it's almost unusable...

**Comment by tkf** [comment]
I guess the problem is in combination of mumamo.el and python-mode.el, as it works OK when using python.el.  Sorry, I can't give you a solution here.  Both mumamo.el and python-mode.el are too big to find a workaround.  Probably you should open an issue ticket in python-mode.el or switch to python.el.

**Comment by tkf** [comment]
I added #58 for the issue with python-mode.el.  Please comment there if you find something.

**Comment by rhstanton** [comment]
I found a simple workaround:

(setq python-saved-check-command nil)

Mumamo seems to be referencing a variable that's defined in python.el but not in python-mode.el.

**Comment by tkf** [comment]
python-saved-check-command is defined only in the old python.el.  I wonder why it is referenced from python-mode.el.  I guess a better way to fix is to remove the following line from the mode definition `python-mode` in python-mode.el:

``` cl
  (make-local-variable 'python-saved-check-command)
```

Anyway, thanks for the info.

**Comment by tkf** [comment]
I added this in wiki tips, thanks https://github.com/tkf/emacs-ipython-notebook/wiki/Tips
