### ISSUE TITLE
Problem with autocomplete

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#55]
I just installed autocomplete (1.3.1) and now when I type C-c TAB, I get the error message

Error found in callback `on-message': (ein-direct)

**Comment by tkf** [comment]
Probably the same error as in #42?  Please update to the latest developmental version of popup.el and try again.

**Comment by rhstanton** [comment]
I upgraded both autocomplete and popup.el, and I get the same problem. 

1) Simple autocompletion works fine. For example, if I type “ex” and wait, I get a popup menu suggesting “exec”, “exit”, etc. So at least it’s installed approximately correctly.

2) However, although I've set ein:use-auto-complete-superpack to t and ein:complete-on-dot to t, nothing happens when I type a dot. If I type a few characters after the dot, autocompletion works again.

3) If I try to get completion to work manually (either after a dot or anywhere else) by typing C-c TAB (which works fine without autocomplete installed), I get an error in the minibuffer:

Error found in callback `on-message': (ein-direct)

**Comment by rhstanton** [comment]
Reinstalling everything using el-get solved this problem.

**Comment by rhstanton** [comment]
By the way, I'd suggest recommending somewhere that it's best to install everything using el-get. This seems to get around most, if not all, of the problems with inconsistent versions of different packages.

**Comment by tkf** [comment]
Thanks for the suggestion.  I will mention it in the document.
