### ISSUE TITLE
Organize directory

### ISSUE THREAD

**Issue by tkf** [tkf/emacs-ipython-notebook#6]
Putting many files in top level directory is a bit ugly.
But how to do it properly?

relevant: #5
# Directory organization in other projects

Just a quick lookup.
## Lisp code lies under `lisp/` (no subdirectories under it):
- org-mode: http://orgmode.org/w/?p=org-mode.git;a=tree
- GNUS: http://git.gnus.org/cgit/gnus.git/tree/
- ESS: https://svn.r-project.org/ESS/trunk/
- reftex: http://cvs.savannah.gnu.org/viewvc/reftex/?root=auctex

```
% cd ~/.emacs.d/el-get/el-get/recipes
% grep '"lisp"' *.rcp                          
ess.rcp:       :load-path ("lisp")
jdee.rcp:  :load-path ("lisp" "elib"))
nognus.rcp:       :load-path ("lisp")
org-mode.rcp:       :load-path ("." "lisp" "contrib/lisp")
reftex.rcp:       :load-path ("lisp")
session.rcp:       :load-path ("lisp")
```
## Flat (like current EIN):
- helm: https://github.com/emacs-helm/helm
- el-get: https://github.com/dimitri/el-get
  there is `method/` directory for submodules.
  `load-path` is automatically modified.
- magit: https://github.com/magit/magit
  (there are not much submodules.)
- gh.el: https://github.com/sigma/gh.el

**Comment by yyr** [comment]
I dont find official link to back up.. But I think The directory structure of org-mode is the standard way. 

For eg: in org mode case, only the files under 

doc/
lisp/
etc/

be synced to Emacs. All other directories and top level files will not go into official Emacs. Cedet is restructured recently similar to other official packages. 

In any way, refactoring to sub directories is a good idea.

Just my 2c

**Comment by tkf** [comment]
@yyr Thanks for the info.  It helps me to decide what to do.  I think having a `lisp/` directory is way to go.

I found Emacs's README helpful for directory organization
https://github.com/emacsmirror/emacs
