### ISSUE TITLE
Version control with EIN?

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#61]
It would be great to integrate EIN with Emacs version control, e.g., VC.

Right now, if I open a notebook, then type C-x v v (the usual command to check in/out), I get an error:

Debugger entered--Lisp error: (error "Buffer _ein: 8888/analyze_ is not associated with a file")
  signal(error ("Buffer _ein: 8888/analyze_ is not associated with a file"))
  error("Buffer %s is not associated with a file" "_ein: 8888/analyze_")
  vc-deduce-fileset(nil t state-model-only-files)
  vc-next-action(nil)
  call-interactively(vc-next-action nil nil)

This occurs even though the .ipynb file is actually under version control (Hg). It would be a huge convenience if I could not only edit and run the notebook, but also check in/out different versions from within the notebook buffer.

**Comment by tkf** [comment]
It seems that `C-x v v` (vc-next-action) requires the current buffer to be a file.  EIN buffer sets directory but not file.  Is there any command in vc.el which needs to know the current directory?  If you use magit (git) or monky (hg), you can start commit from any buffer.

BTW, if you change directory in IPython (for example using `%cd`), current directory of the EIN buffer will be changed.  So be careful not to go out from version controlled directory if you are using VC from EIN buffer.

**Comment by tkf** [comment]
It's an experimental feature, but I think you can use `vc-next-action` by setting `(setq ein:notebook-set-buffer-file-name t)`.
