### ISSUE TITLE
Any way to execute all cells in notebook?

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#63]
Is there a command to execute all cells in the current notebook? If not, can I suggest that this would be a very useful command? Thanks!

**Comment by tkf** [comment]
`M-x ein:notebook-execute-all-cell` should do the job.

**Comment by tkf** [comment]
I am closing this issue as EIN already has this feature.  Please reopen it if you find a problem.

**Comment by jsoishi** [comment]
M-x ein:notebook-execute-all-cell does not appear to be in my version EIN, which I just updated via el-get. I also downloaded the most recent zip file, and notebook-execute-all-cells doesn't appear anywhere in the current codebase. This feature is very useful to me; could it be restored?

**Comment by tkf** [comment]
You are right.  It is renamed to `ein:worksheet-execute-all-cell`.  Also, it should be accessible from somewhere other than `M-x`.  So I am reopening it.

**Comment by tkf** [comment]
You can now run it from "`C-right click` > EIN Notebook > Cell/Code > Execute all".

**Comment by vellamike** [comment]
C-right click > EIN Notebook > Cell/Code > Execute all". doesn't work for me?

Also, what's wrong with a keybinding like c-c c-f

**Comment by tkf** [comment]
What do you mean by "doesn't work"?  Do you have drop down list but not "execute all" entry?  Or you have the entry but clicking it does not do anything?

The reason why I did not define keybind was that EIN has too many commands.  You can always add it in your Emacs setup.

**Comment by jsoishi** [comment]
Just to confirm, it works great for me.

Thanks!

**Comment by OldIMP** [comment]
wonder if there's a way to execute all **previous** cells, which would be really helpful since sometimes i'm not finished w/ the cells below and those happen to be very time consuming. Thx!
