### ISSUE TITLE
Prompt loses formatting when cursor moves into input cell

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#64]
This is minor...

I've noticed that when I move the cursor into an input cell, after some fraction of a second the prompts in the notebook change the way they're displayed. In particular, they no longer appear in raised boxes, and their color reverts to the notebook default. When I move the cursor out of the input cell, the original formatting returns.

**Comment by tkf** [comment]
Yes, it's a bit annoying...  This is a known problem http://tkf.github.com/emacs-ipython-notebook/#id11.  I guess it is MuMaMo's bug.  So there is not much I can do in EIN.
