### ISSUE TITLE
"Text is read-only" in notebook

### ISSUE THREAD

**Issue by demon386** [tkf/emacs-ipython-notebook#66]
I can't insert any character in the notebook input buffer. It prompts "Text is read-only" whenever I press a key.

I'm using emacs 24.1 and IPython 0.13 under Mac.

**Comment by tkf** [comment]
You mean in the input area (which has slightly different background color)?  Outside of this area, text is read-only.

**Comment by demon386** [comment]
Yeah. Let me give you a screen flow to see if I was doing anything wrong.

http://d.pr/v/E1au

**Comment by tkf** [comment]
Thanks for taking time to take a video.  You need to insert a cell before typing anything.  So hit `C-c C-b` (insert cell below) to insert the first cell.  Come to think of it, it is better to insert a new cell when opening a notebook without a cell.  I will add this feature later.

**Comment by demon386** [comment]
Got it. Thanks.
