### ISSUE TITLE
Cell output sometimes doesn't display

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#68]
Every now and then, I find that a cell will not display its output when I press Alt-Enter. The calculation seems to complete OK, but all I see in the output area is a dot or two. If I create a new input cell, copy the contents of the old cell, and press Alt-Enter again, the new cell works fine, but the original cell never works, regardless of what command I put in it.

Here's an example which shows the same problem under both Windows and OS X:

 [Example notebook file](http://faculty.haas.berkeley.edu/stanton/misc/test.zip)

**Comment by tkf** [comment]
You can toggle visibility of the output by `C-c C-e`.  If you have many cells like this, you can make output of all cells visible by `C-u C-c C-v`.
See also http://tkf.github.com/emacs-ipython-notebook/#notebook

**Comment by rhstanton** [comment]
Thanks. So many features…!

Unfortunately, when I press C-u C-c C-v, I get a brief message saying “Entering debugger”, then Emacs hangs permanently!

**Comment by tkf** [comment]
Thanks for the report.  Indeed, there was a bug in `C-u C-c C-v`.  I quickly fixed it so there should be no problem now.

If you are going to update EIN, be sure close all notebooks (or, even better, reboot Emacs) before updating.

BTW, the document is wrong about what `(C-u) C-c C-v` does.  `C-c C-v` shows everything and `C-u C-c C-v` hides everything.  It is opposite in the document.

**Comment by rhstanton** [comment]
That works now. Thanks.
