### ISSUE TITLE
Suggestion: menus

### ISSUE THREAD

**Issue by rhstanton** [tkf/emacs-ipython-notebook#69]
EIN has so many different features it's hard to keep track. Even though I rarely use menus, this is one package that could really benefit from them, as they'd make it much easier to find all the various functions available.

**Comment by tkf** [comment]
I just added very simple menu in notebook mode.  Please check it out.  One thing I couldn't make it is to access menu from mode-line when MuMaMo is on.  So you need Emacs menu bar (or Ctrl + right click) to access the menu.

@gabrielelanaro I guess you are interested in this feature as you mentioned in #9.

**Comment by rhstanton** [comment]
That’s a big help. Thanks!

**Comment by gabrielelanaro** [comment]
I'll definitely test it!
