### ISSUE TITLE
Make emacs-ipython-notebook available on Marmalade or Melpa

### ISSUE THREAD

**Issue by bastibe** [tkf/emacs-ipython-notebook#7]
In addition to el-get, please make the project available for the Emacs24 built-in package manager `package.el`

**Comment by tkf** [comment]
Thanks for your interest.  I will register EIN in Melpa after reconsidering directory organization (#6).  Probably Marmalade also, after websocket.el (EIN's mandatory dependency) is available in there.

**Comment by bastibe** [comment]
Since melpa and marmalade are compatible, either is probably enough.

**Comment by tkf** [comment]
I sent pull requests to MELPA for websocket.el (milkypostman/melpa#185) and EIN (milkypostman/melpa#186).  After these two are merged, you can install them via MELPA.

I couldn't find recipe for nxhtml (MuMaMo). I found a branch having it, but I don't know why it is merged.
https://github.com/milkypostman/melpa/tree/nxhtml

**Comment by tkf** [comment]
The recipe for EIN is merged in MELPA.  Now you can install it from MELPA.  It seems that the recipe for websocket.el will take for a while.

**Comment by milkypostman** [comment]
@tkf because I felt the nxhtml package needed some testing before merging....

**Comment by tkf** [comment]
@milkypostman thanks for the clarification!  I am looking forward it to be merged.

**Comment by tkf** [comment]
Closing this as EIN and its minimal requirement is in MELPA.

**Comment by bastibe** [comment]
Thanks a bunch! I just tried it and I am _loooving_ it!

**Comment by tkf** [comment]
Good to know you like it!  And it's good to know it works, because only user reports I've got are "it doesn't work" and "install failed" :)

**Comment by milkypostman** [comment]
Could be install fails because `websockets.el` is not a dependency and it's not getting automatically installed?

**Comment by tkf** [comment]
I don't know much about package.el so I am not sure.  Compilation will fail when websocket.el is not on the path, but EIN should be usable (though slow) if it gets installed.
