### ISSUE TITLE
el-get install borked

### ISSUE THREAD

**Issue by mattharrison** [tkf/emacs-ipython-notebook#77]
Have a fresh el-get (MASTER) install on emacs 24.2. Both `el-get-install` and `el-get-reinstall` fail to work.

I get the following error:

`ein:notebooklist-ask-url-or-port: Symbol's function definition is void: ein:get-notebook`

**Comment by tkf** [comment]
Hmm.  That's strange.  Do you have ~/.emacs.d/el-get/ein/lisp/ein-core.el?  If so, can you try loading it (`M-x load-library RET ein-core RET`) before `el-get-reinstall`?

**Comment by tkf** [comment]
Please tell me the git revision and ein:version of EIN and ein:version before calling el-get-reinstall if you remember, for future reference.

**Comment by mattharrison** [comment]
Hmmm, running `load-library` appeared to do the trick.

`ein:version` is "0.2.0.alpha0"

git rev is 34c48ff8f42661bfe1248bfcbd2d8d20d5b29051

**Comment by tkf** [comment]
Good.  But I still don't understand why ein:notebooklist-ask-url-or-port tries to access ein:get-notebook when installing it.

You have empty (or no) ~/.emacs.d/el-get/ directory before installing EIN, right?  Especially, no ~/.emacs.d/el-get/.loaddefs.el?  My guess was that .loaddefs.el does something wrong but it does not exist at install time I have no idea why it went wrong.

**Comment by tkf** [comment]
I ran this to test clean install using el-get:

  HOME=/tmp/test-el-get-ein emacs -Q -batch -L ~/.emacs.d/el-get/el-get --eval "(require 'el-get)" --eval "(make-directory el-get-dir t)" --eval "(el-get 'sync 'ein)"

It works fine in Emacs 23.3.1 and 24.50.1 in Ubuntu 11.10.

So I suppose your ~/.emacs.d/el-get before installing EIN is not really in "clean state".  I think el-get should handle update but there are some bugs in el-get.

**Comment by tkf** [comment]
I am closing this issue.  Of course, some followup information is very welcome :)
