### ISSUE TITLE
ginput() doesn't work

### ISSUE THREAD

**Issue by pranjalv123** [tkf/emacs-ipython-notebook#83]
Hi, 
If I try to use ginput() in ein, I get an error (below). Is this supported in EIN, or am I doing something wrong?

Truncated Traceback (Use C-c C-x to view full TB):
/usr/local/lib/python2.7/dist-packages/matplotlib/blocking_input.pyc in **call**(self, n, timeout)
     92 
     93         # Ensure that the figure is shown

---> 94         self.fig.show()
     95 
     96         # connect the events to the on_event function call

AttributeError: 'Figure' object has no attribute 'show'

**Comment by tkf** [comment]
Hi, thanks for the report.  But please try to put enough information for me to reproduce the issue.  I don't know what is `ginput`.  I assume you are using `--pylab=inline` or something.  If so, it is from `pylab` namespace.  Also, did you try the same in official browser frontend?

**Comment by pranjalv123** [comment]
ginput gives the location of clicks on the figure. This looks like it's
also a problem in the online notebook with --pylab inline. I'll see if it's
been worked out there. Thanks!

## 

Pranjal Vachaspati

**Comment by tkf** [comment]
I am closing this issue as it is not EIN's issue.
