### ISSUE TITLE
fill-paragraph in markdown cell

### ISSUE THREAD

**Issue by markusbaden** [tkf/emacs-ipython-notebook#84]
When running fill-paragraph in a markdown cell I get the message 

```
fill-delete-newlines: Text is read-only
```

However marking a region and then running fill-region works as expected, so I was wondering whether I can get fill paragraph to work within EIN as well.

**Comment by markusbaden** [comment]
Sorry for the quick update, but I noticed that fill-paragraph sometimes works and sometimes does not. It seems when there is a preceeding paragraph, I can fill-paragraph the next one without problems. See the gist at https://gist.github.com/4138809 for a minimal notebook showing the behaviour. To replicate, open it in EIN and try to fill-paragraph in the first cell or in the second paragraph of the second cell.

**Comment by tkf** [comment]
Yes, I noticed that behavior.  This is because at the beginning and end of input area I need to put some unusual text properties.  Give me some time to workaround this issue.  If you put empty lines at the beginning and end of input area, fill-paragraph should work.

**Comment by tkf** [comment]
I added a fix.  Please try the latest version.

**Comment by markusbaden** [comment]
Thanks for the quick fix. fill-paragraph works fine now!
