### ISSUE TITLE
File name completion not working

### ISSUE THREAD

**Issue by maximsch2** [tkf/emacs-ipython-notebook#86]
Web notebook has the ability to complete filenames: when I write 
  open("~/data/bla/
it offers as a completion all files/dirs in that directory.

This doesn't seem to be working in EIN.

**Comment by tkf** [comment]
Thanks.  I didn't notice as I am using IPython from EIN all the time.  Fixed in the latest master.

**Comment by maximsch2** [comment]
Thank you for a quick fix! Can you describe how you are using IPython console from EIN? Maybe a blog post somewhere about the whole setup?

**Comment by tkf** [comment]
By IPython console you mean `ein:console-open`?
You can find how to setup it in the manual http://tkf.github.com/emacs-ipython-notebook/#console
But I agree that the documentation is not super friendly.

Or, if you just want to try something without saving it on notebook, use `ein:notebook-scratchsheet-open` (`C-c C-/`).  It's like qtconsole in Emacs.

**Comment by tkf** [comment]
Basically, if you just run one notebook server on local machine it should not be difficult to setup ein:console.  Just add this in your Emacs setup:

``` cl
(setq ein:console-args "--profile YOUR-IPYTHON-PROFILE")
```

The default value of `ein:console-args` is `"--profile nbserver"`.  If you never made IPython profile by yourself,

``` cl
(setq ein:console-args "--profile default")
```

should work.  If you have further questions, just open another issue.
