### ISSUE TITLE
EIN menu

### ISSUE THREAD

**Issue by gabrielelanaro** [tkf/emacs-ipython-notebook#9]
Is an EIN menu planned? I think a menu would help users to explore the various commands in the EIN package.

**Comment by tkf** [comment]
That would be a nice feature.  But I have no plan for that, as I don't use menu (anything/helm is enough for me) and I don't know how to write it.  Maybe I will try it sometime later, but if somebody wants to try to implement it, patches are very welcome.

**Comment by gabrielelanaro** [comment]
Thank you for your insights! Then I'll reopen this if I find some time to implement it
