### ISSUE TITLE
Scrolling notebooks with images

### ISSUE THREAD

**Issue by maximsch2** [tkf/emacs-ipython-notebook#94]
Scrolling in Emacs is strange. To fix that I've tried to switch emacs-mac-app (Emacs Mac port), which does a lot better job at scrolling overall (and it feels like EIN is working faster in it too). But I am still experiencing problems. Namely, if I have an image close to the end of the notebook, scroll to the bottom of the notebook (image is not visible at this point) then I get stuck - I cannot scroll up using the trackpad gesture (using up keyboard button works though). Is it possible to fix it somehow from EIN's side?

**Comment by tkf** [comment]
If it happens only in that version of Emacs (patched version?), I guess fixing that Emacs sounds straight forward approach.  Who build that Emacs?  Can you send an issue report to there?

**Comment by maximsch2** [comment]
Image scrolling in the original emacs is jumpy too (there is no way to
smoothly scroll through image that is bigger then the screen). I've come
across this blog post (admittedly old one)
http://www.randomsample.de/dru5/node/25 and it talks about some image-mode
providing better smoother scrolling for images. So I was thinking that
maybe it is possible for EIN to use image-mode for the areas containing
images. I am relatively new to emacs, sorry if it doesn't make sense.

Maxim Grechkin

**Comment by tkf** [comment]
Actually I think I have the same problem in normal Emacs (24.1.50.1) in Ubuntu.  I guess I've never shown the image larger than window height.  When I use scroll using C-n, I can't see the bottom part of the image because the last scroll is so big.  When I scroll using C-v, pressing once just cause the buffer to shudder (image goes up once and come back to the original position).  Keep pressing it just skips the image.  Is it the problem you have?

**Comment by tkf** [comment]
I guess the best fix is to use "sliced image" as the blog post mentioned.
http://www.gnu.org/software/emacs/manual/html_node/elisp/Showing-Images.html

**Comment by maximsch2** [comment]
Yes, the effect is very similar to what you are describing, although I am
using touchpad to scroll. I can confirm that changing line in ein-cell.el
to:
      (insert-sliced-image (create-image (base64-decode-string value) key
t) "blabla" nil 20 20)))))
seems to fix the scrolling, although it breaks up the image and
significantly slows down the Emacs. Short googling again points to the same
blog: http://www.randomsample.de/dru5/node/24 (this seems to be related to
the breaking up of the image - there is small space between the lines that
we want to get rid of)

Maxim Grechkin

**Comment by tkf** [comment]
Hmm... slowing down Emacs is not good.  I guess you can omit COLS part, like this.  Not sure if it helps though.

``` cl
(insert-sliced-image (create-image (base64-decode-string value) key t) nil nil 20)
```

Re: spaces, do you see space between columns?  What is the value of your `line-spacing` in the notebook buffer?

**Comment by maximsch2** [comment]
Yes, omitting COLS part makes Emacs snappier, and scrolling works a lot
better now too. There are no spaces between columns, but
there definitely is some line spacing. How can I look measure it's value?

Is there a way EIN could estimate the size of the image and adaptively
compute the number of rows needed to make scrolling robust?

Maxim Grechkin

**Comment by tkf** [comment]
I've never used but I guess `image-size` is for calculating image size.

If I run

``` python
pyplot.figure()
pyplot.plot()
pyplot.figure()
pyplot.plot()
```

I see two images without space between them.  So I guess space depends on Emacs config.  My `line-spacing` is `nil`.  What is yours?

It is possible to deal with this value with text property just for line where image is.  But setting `line-spacing` is easier solution.  At least for now.

**Comment by twiecki** [comment]
Running into this problem as well. Is adding

``` lisp
(insert-sliced-image (create-image (base64-decode-string value) key t) nil nil 20)
```

still the preferred fix? Which line in `ein-cell.el` do I have to change?

**Comment by tkf** [comment]
I add an experimental configuration variable `ein:slice-image`.  You can split image by:

``` cl
(setq ein:slice-image t)  ; ROWS=20, COLS=nil
```

If you want more split (say, ROWS=100, COLS=30) then

``` cl
(setq ein:slice-image '(100 30))
```

Better way would be to calculate image size and determine ROWS and COLS.  I am not planning to do this by myself but patches are welcome.

**Comment by twiecki** [comment]
Thanks, works like a charm!
Also, I find ein to be a much more effective IPyNB interface than the html/js one. Use it for all my data analysis so thanks for creating it!

**Comment by tkf** [comment]
Be careful with `ein:slice-image` when plotting data.  I tried it a bit and I found sometimes you miss nearly-horizontal lines.  Hopefully you don't miss any findings because of EIN :)

**Comment by twiecki** [comment]
Ah yeah, I noticed that `slice-image` seems to cut out a single line at the slice. Is that a slice-image bug (I suppose this is external functionality)?

**Comment by tkf** [comment]
I think Emacs is linked with imagemagic or something.  `insert-sliced-image` is implemented in lisp, so probably there could be a bug in image.el.

**Comment by twiecki** [comment]
Do you happen to know the correct party to address this to? Would be good to get this fixed.

**Comment by tkf** [comment]
I think the "best" way to do this is to actually fix scroll.  So you may want to ask it in emacs dev mailing list.

**Comment by twiecki** [comment]
OK, I posted to emacs-bugs here:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2013-06/msg00116.html

**Comment by tkf** [comment]
Cool!

**Comment by ramestica** [comment]
Hello,

the ein:slice-image solution almost work for me. Unfortunately, every time I press enter while at the end of a line within a python code block then the images  are replaced by many lines that except for the first character being a symbol are blank lines. I need to re-evaluate on each block to get the images back.

Anything I should check in my configuration?

Thanks,
 Rodrigo

emacs 24.3.1
ein.el Version: 0.2.1alpha2
