### ISSUE TITLE
Package install fails to compile ein-mumamo.el with error: Cannot open load file: mumamo

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [tkf/emacs-ipython-notebook#99]
I am trying to install ein using `M-x package install`

I have the following package sources:

```
(setq package-archives '(("ELPA" . "http://tromey.com/elpa/") 
                          ("gnu" . "http://elpa.gnu.org/packages/")
                          ("marmalade" . "http://marmalade-repo.org/packages/")
                          ("melpa" . "http://melpa.milkbox.net/packages/")
))
```

However, when I run `M-x package install RET` I get the error:

```
Compiling file /home/XXX/.emacs.d/elpa/ein-20130118.1403/ein-mumamo.el at Tue Jan 22 14:07:29 2013
ein-mumamo.el:28:1:Error: Cannot open load file: mumamo
```

Any thoughts?

**Comment by tkf** [comment]
Dependency on mumamo is optional so you can ignore it.  Is it just compile error or the installation fails?

**Comment by amelio-vazquez-reina** [comment]
Thanks tkf. It looks like it works if I ignore the compilation error. When working on a notebook, ein froze Emacs though, but I will try again soon.

**Comment by tkf** [comment]
OK, I will close this issue.  Please use M-x ein:dev-bug-report-template if you need to ask something.
